spring.application.name=financial_audit

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DataSource settings
spring.datasource.url=jdbc:h2:mem:auditdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=financial_audit
spring.datasource.password=WrEXD5.!BByV~K.

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
